# Generated by Django 3.1.4 on 2020-12-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tweet_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='userlikes',
            field=models.ManyToManyField(related_name='_tweet_userlikes_+', to='main.Tweet'),
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('hashToTweet', models.ManyToManyField(to='main.Tweet')),
            ],
        ),
    ]
