# Generated by Django 3.1.4 on 2020-12-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201203_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='userlikes',
            new_name='likes',
        ),
    ]
