# Generated by Django 3.1.4 on 2020-12-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201203_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(to='main.UserLikes'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='user',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
