# Generated by Django 3.1.4 on 2020-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201203_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='user',
        ),
        migrations.AddField(
            model_name='userlikes',
            name='current',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
