# Generated by Django 3.1.4 on 2020-12-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201203_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='current',
        ),
    ]
