# Generated by Django 3.1.4 on 2020-12-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201203_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(to='main.UserLikes'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='user',
            field=models.CharField(default='', max_length=200),
        ),
    ]
